### ISSUE TITLE
Report page oversight with penalty notification

### ISSUE THREAD

**Issue by Koishukaze** [33mamaster/LC-LifetimeCruiserWarranty#1]
When leaving a moon without the cruiser, LifetimeCruiserWarranty (LCW) shows its penalty screen by skipping through the report

https://github.com/user-attachments/assets/7a4f0ae4-336f-4e73-a7cc-3413d977d488

**Comment by 33mamaster** [comment]
Thanks for this.
Its actually a known issue (as why I disabled this feature by default), I just became too busy to fix.

With more time since then, I think as temporary fix, I'll just move the warning elsewhere until I can fix it properly.
I'll work on the temporary fix asap since this really has been broken for too long.

**Comment by 33mamaster** [comment]
Deployed a fix. Its on Thunderstore now, and should be on r2modman when it next syncs (30 minutes give or take)

I've moved the penalty notification into the tips UI.
It appears at the end in the bottom right.

![image](https://github.com/user-attachments/assets/b298d048-2e98-4028-84c6-77db1bc124d4)
